name: Go release builder

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
           
    - name: Build
      run: cd app && go get main && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o monitor

    - name: Test
      run: cd app && go test
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.tag }}
        release_name: Release ${{ github.tag }}
#         body: |
#           Changes in this Release
#           - First Change
#           - Second Change
        body_path: |
          app/monitor
        draft: false
        prerelease: false
    
#     - name: Build release
#       uses: "marvinpinto/action-automatic-releases@latest"
#       with:
#         repo_token: "${{ secrets.GITHUB_TOKEN }}"
# #         automatic_release_tag: ${{ github.tag }}
#         prerelease: false
#         title: Release ${{ github.ref }}
#         files: |
#           app/monitor
