name: Go release builder

on:
  push:
#     tags:
#       - 'v*'
    branches:
      - "master"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
           
    - name: Build
      run: cd app && go get main && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o monitor
       
    - name: Build release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#         automatic_release_tag: ${{ github.tag }}
        prerelease: false
        title: Release ${{ github.ref }}
        files: |
          app/monitor
